### Get Logged In User

### Route GET /api/user/me
GET http://localhost:3005/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDJhMzg4NTM5MGYyMzc0Yzk1OTlhNyIsImlhdCI6MTYyNzU2Mjg4OH0.5DQuH6KVXTjMRQnH-ZP9tLhMrPt55M6T7wSQPV5xkFs

### Route PUT /api/user/update/name
PUT http://localhost:3005/api/user/update/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDJhMzg4NTM5MGYyMzc0Yzk1OTlhNyIsImlhdCI6MTYyNzU2Mjg4OH0.5DQuH6KVXTjMRQnH-ZP9tLhMrPt55M6T7wSQPV5xkFs

{
    "name":"Anurag Kumar"
}

### Route POST /api/user/request
POST  http://localhost:3005/api/user/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDJhMzg4NTM5MGYyMzc0Yzk1OTlhNyIsImlhdCI6MTYyNzU2Mjg4OH0.5DQuH6KVXTjMRQnH-ZP9tLhMrPt55M6T7wSQPV5xkFs

{
    "uid": 1503619500
}


### Route DELETE /api/user/request
DELETE  http://localhost:3005/api/user/request
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDJhMzg4NTM5MGYyMzc0Yzk1OTlhNyIsImlhdCI6MTYyNzU2Mjg4OH0.5DQuH6KVXTjMRQnH-ZP9tLhMrPt55M6T7wSQPV5xkFs

{
    "uid": 1271476664
}

### Route GET /api/user/:uid
GET  http://localhost:3005/api/user/profile/1271476664
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDJhMzg4NTM5MGYyMzc0Yzk1OTlhNyIsImlhdCI6MTYyNzU2Mjg4OH0.5DQuH6KVXTjMRQnH-ZP9tLhMrPt55M6T7wSQPV5xkFs